DemoBuikAlp1/DemoBuikAlp1/Controllers/BuilkProject1Controller.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BuikSiteWalkModel1.ModelEntities;
using BuikSiteWalkModel1.Repository;
using BuikSiteWalkModel1.Abstract;
using Microsoft.WindowsAzure.Storage.Blob;
using DemoBuikAlp1.StorageService;
using System.IO;
using Microsoft.WindowsAzure.Storage;
using System.Configuration;

namespace DemoBuikAlp1.Controllers
{   
    //[Authorize]
    public class BuilkProject1Controller : Controller
    {
        EFIssueRepository irepo = new EFIssueRepository();
        IUserRepository urepo = new EFUserRepository();
        IProjectRepository prepo = new EFProjectRepository();
        

        #region MobileService

        private List<BuikProjectEntity> GetProjectListByEmail(string uname)
        {
            List<BuikProjectEntity> res = new List<BuikProjectEntity>();
            try
            {
                res = prepo.GetProjectMobileEntityByCollaborationIdEmail(uname);
            }
            catch { return res; }
            return res;
        }
        private ActionResult ProjectViewMobile(string uemail)
        {
            List<BuikProjectEntity> r = prepo.GetProjectMobileEntityByCollaborationIdEmail(uemail);

            return Json(r, JsonRequestBehavior.AllowGet);
        }
        private int pAddProjectIssueComment(string comment, int issueid, int userid)
        {
            return irepo.AddProjIssueComment(userid, issueid, comment);
        }
        private int pAddIssueLike(Int32 issueid, Int32 userid)
        {
            return irepo.AddLikeIssue(issueid, userid);
        }

        public ActionResult GetAllProjectType()
        {
            var res = prepo.GetAllProjectType();
            return Json(res, JsonRequestBehavior.AllowGet);
        }
        public ActionResult IndexMobileNew(string email)
        {
            var p = prepo.GetProjectDetailMobileByEmail(email);//GetProjectListByEmail(uname);
            
            return Json(p,JsonRequestBehavior.AllowGet);
        }

        public ActionResult GetAllProjectList(string email)
        {
            var p = prepo.GetProjectMobileEntityByCollaborationIdShowAll(urepo.GetUserIdByEmail(email));//GetProjectListByEmail(uname);

            return Json(p, JsonRequestBehavior.AllowGet);
        }

        public ActionResult UpdateProjectCompany(Int32 prid, Int32 compid)
        {
            try
            {
                return Json(prepo.UpdateProjectCompany(prid, compid),JsonRequestBehavior.AllowGet);
            }
            catch { return Json("0",JsonRequestBehavior.AllowGet); }
        }

        public ActionResult GetProjectDetailById(Int32 prid)
        { 
            var p = prepo.GetProjectDetailByPrid(prid);
            return Json(p, JsonRequestBehavior.AllowGet);
        }

        public ActionResult SetProjectAsFav(Int32 uid,Int32 prid) 
        {
            return Json(prepo.SetProjAsFav(uid, prid, 1),JsonRequestBehavior.AllowGet);
        }
        public ActionResult UnsetProjAsFav(Int32 uid, Int32 prid) 
        {
            return Json(prepo.SetProjAsFav(uid, prid, 0),JsonRequestBehavior.AllowGet);
        }
        public ActionResult SetProjectShow(Int32 uid, Int32 prid)
        {
            return Json(prepo.SetCollaborationShow(prid, uid), JsonRequestBehavior.AllowGet);
        }
        public ActionResult SetProjectHide(Int32 uid, Int32 prid)
        {
            return Json(prepo.SetCollaborationHide(prid, uid),JsonRequestBehavior.AllowGet);
        }


        public ActionResult IndexMobile()
        {
            //var p = prepo.GetProjectMobileEntityByCollaborationId((string)Session["UserDisplayName"]);
            List<BuikProjectEntity> p = new List<BuikProjectEntity>(); 
            if(Session["UserEmail"] != null)
            {
                p = GetProjectListByEmail(Session["UserEmail"].ToString()).OrderByDescending(r=> r.IsFav).ThenBy(q => q.prid).ToList();
            }
            return Json(p,JsonRequestBehavior.AllowGet);
        }       

        public ActionResult AddNewProjectMobile(Int32 userid,string pname,string cname,string ptype,string pprovince,string pcountry,string psdate,string pedate)
        {
            if(Session["UserDisplayName"] == null)
                Session["UserDisplayName"] = "Anonymous";
            BuikProjectEntity p = new BuikProjectEntity();
            p.ProjectName = pname;
            p.CustomerName = cname;
            p.ProjectType = ptype;
            p.ProjectCountry = pcountry;
            p.ProjectProvince = pprovince;
            p.ProjectStartDate = psdate;
            p.ProjectEndDate = pedate;
            //p.CreateUserName = userid;//Session["UserDisplayName"].ToString();
            p.createuserid = userid;
            string res = prepo.AddNewProjectMobile(p);
            if (Convert.ToInt32(res) < 1)
            {
                res = "Unable to Add Project Data";
                return Json(res, JsonRequestBehavior.AllowGet);
            }
            else
            {  Session["ProjectID"] = res;
                 
            return Json(res,JsonRequestBehavior.AllowGet);}
        }

        public ActionResult AddNewProjectMobileWithLat(Int32 userid, string pname, string cname, string ptype, string pprovince, string pcountry, string psdate, string pedate,string lat,string longt)
        {
           
            BuikProjectEntity p = new BuikProjectEntity();
            p.ProjectName = pname;
            p.CustomerName = cname;
            p.ProjectType = ptype;
            p.ProjectCountry = pcountry;
            p.ProjectProvince = pprovince;
            p.ProjectStartDate = psdate;
            p.ProjectEndDate = pedate;
            //p.CreateUserName = userid;//Session["UserDisplayName"].ToString();
            p.createuserid = userid;
            p.latitude = Convert.ToDecimal(lat);
            p.longtitude = Convert.ToDecimal(longt);

            string res = prepo.AddNewProjectMobileWithLat(p);
            if (Convert.ToInt32(res) < 1)
            {
                res = "Unable to Add Project Data";
                return Json(res, JsonRequestBehavior.AllowGet);
            }
            else
            {
               // Session["ProjectID"] = res;
                return Json(res, JsonRequestBehavior.AllowGet);
            }
        }
       

        public ActionResult AddNewProjectMobileWithPhoto(Int32 userid, string pname, string cname, string ptype, string pprovince, string pcountry, string psdate, string pedate,HttpPostedFileBase pcoverphoto)
        {
            if (Session["UserDisplayName"] == null)
                Session["UserDisplayName"] = "Anonymous";
            BuikProjectEntity p = new BuikProjectEntity();
            p.ProjectName = pname;
            p.CustomerName = cname;
            p.ProjectType = ptype;
            p.ProjectCountry = pcountry;
            p.ProjectProvince = pprovince;
            p.ProjectStartDate = psdate;
            p.ProjectEndDate = pedate;
            //p.CreateUserName = Session["UserDisplayName"].ToString();
            p.createuserid = userid;
            p.ProjectTimelinePhoto = SavePhotoToStorage(pcoverphoto,"CoverPhoto");
            string res = prepo.AddNewProjectMobile(p);
            if (Convert.ToInt32(res) < 1)
            {
                res = "Unable to Add Project Data";
                return Json(res, JsonRequestBehavior.AllowGet);
            }
            else
            {
                Session["ProjectID"] = res;

                return Json(res, JsonRequestBehavior.AllowGet);
            }
        }


        public ActionResult AddNewProjectMobileWithPhotoPath(Int32 userid, string pname, string cname, string ptype, string pprovince, string pcountry, string psdate, string pedate, string photopath)
        {
            if (Session["UserDisplayName"] == null)
                Session["UserDisplayName"] = "Anonymous";
            BuikProjectEntity p = new BuikProjectEntity();
            p.ProjectName = pname;
            p.CustomerName = cname;
            p.ProjectType = ptype;
            p.ProjectCountry = pcountry;
            p.ProjectProvince = pprovince;
            p.ProjectStartDate = psdate;
            p.ProjectEndDate = pedate;
            //p.CreateUserName = Session["UserDisplayName"].ToString();
            p.createuserid = userid;
            p.ProjectTimelinePhoto = photopath;//SavePhotoToStorage(pcoverphoto, "CoverPhoto");
            string res = prepo.AddNewProjectMobile(p);
            if (Convert.ToInt32(res) < 1)
            {
                res = "Unable to Add Project Data";
                return Json(res, JsonRequestBehavior.AllowGet);
            }
            else
            {
                Session["ProjectID"] = res;

                return Json(res, JsonRequestBehavior.AllowGet);
            }
        } 
        
        //Not Implemented
        public ActionResult AddProjectCoverPhotoMobilePath(string pathphoto, int projectid)
        {
            //string fpath = SavePhotoToStorage(photo, "CoverPhoto");
            string res = prepo.UpdateProjectProfilePhoto(projectid, pathphoto);
            return Json(res, JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        public string AddProjecFloorPalnMobileEE(HttpPostedFileBase photo, int projectid)
        {
            string fpath = SavePhotoToStorage(photo, "FloorPlan"+projectid.ToString());
            string res = prepo.UpdateProjectProfilePhoto(projectid, fpath);
            return res;// Json(res, JsonRequestBehavior.AllowGet); 
        }

        public ActionResult AddProjecFloorPalnMobilePath(string pathphoto, int projectid)
        {

DemoBuikAlp1/DemoBuikAlp1/Views/BuilkProject1/AddNewProject-Old.cshtml
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary()
}
@model BuikSiteWalkModel1.ModelEntities.BuikProjectEntity
@{
    ViewBag.Title = "Add New Project";
}

<h2>AddNewProject</h2>    
    
 <fieldset>
        <legend>Registration Form</legend>
        <ol>
            <li>
                @Html.LabelFor(m => m.ProjectName)
                @Html.TextBoxFor(m => m.ProjectName)
            </li>
            <li>
                @Html.LabelFor(m => m.CustomerName)
                @Html.TextBoxFor(m => m.CustomerName)
            </li>
            <li>
                @Html.LabelFor(m => m.ProjectType)
                @Html.DropDownListFor(m => m.ProjectType,)
            </li>
            <li>
                @Html.LabelFor(m => m.ProjectLocation)
                @Html.TextBoxFor(m => m.ProjectLocation)
            </li>
            <li>
                @Html.LabelFor(m => m.ProjectTimelinePhoto)
                @Html.PasswordFor(m => m.ProjectTimelinePhoto)
            </li>
            <li>
                @Html.LabelFor(m => m.ProjectStartDate)
                @Html.DropDownListFor(m => m.ProjectStartDate)
            </li>
            <li>
                @Html.LabelFor(m => m.ProjectEndDate)
                @Html.DropDownListFor(m => m.ProjectEndDate)
            </li>
            <li>
                @Html.LabelFor(m => m.ProjectTimelinePhoto)
                @Html.TextBoxFor(m => m.ProjectTimelinePhoto)
            </li>
        </ol>
        <input type="submit" value="Register" />
    </fieldset>




DemoBuikAlp1/DemoBuikAlp1/Views/BuilkProject1/AddNewProject.cshtml
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary()
}
@model BuikSiteWalkModel1.ModelEntities.BuikProjectEntity
@{
    ViewBag.Title = "Add New Project";
}

<h2>AddNewProject</h2>    
    
 <fieldset>
        <legend>Registration Form</legend>
        <ol>
            <li>
                @Html.LabelFor(m => m.ProjectName)
                @Html.TextBoxFor(m => m.ProjectName)
            </li>
            <li>
                @Html.LabelFor(m => m.CustomerName)
                @Html.TextBoxFor(m => m.CustomerName)
            </li>
            <li>
                @Html.LabelFor(m => m.ProjectType)
                @Html.DropDownListFor(m => m.ProjectType)
            </li>
            <li>
                @Html.LabelFor(m => m.ProjectLocation)
                @Html.TextBoxFor(m => m.ProjectLocation)
            </li>
            <li>
                @Html.LabelFor(m => m.ProjectTimelinePhoto)
                @Html.PasswordFor(m => m.ProjectTimelinePhoto)
            </li>
            <li>
                @Html.LabelFor(m => m.ProjectStartDate)
                @Html.DropDownListFor(m => m.ProjectStartDate)
            </li>
            <li>
                @Html.LabelFor(m => m.ProjectEndDate)
                @Html.DropDownListFor(m => m.ProjectEndDate)
            </li>
            <li>
                @Html.LabelFor(m => m.ProjectTimelinePhoto)
                @Html.TextBoxFor(m => m.ProjectTimelinePhoto)
            </li>
        </ol>
        <input type="submit" value="Register" />
    </fieldset>




DemoBuikAlp1/DemoBuikAlp1/Views/BuilkProject1/UploadPP44.cshtml
@{
    ViewBag.Title = "UploadPP44";
}



<h2>Upload Image</h2>
<p>
@using (Html.BeginForm("UploadPP44", "BuilkProject1", FormMethod.Post, new { enctype = "multipart/form-data" }))
{ 
    <input type = "file" name="image" />
    <input type = "submit" value="Upload" />
    
}
</p>

DemoBuikAlp1/DemoBuikAlp1/Views/BuilkProject1/UploadTvT.cshtml
@{
    ViewBag.Title = "UploadTvT";
}

<h2>UploadTvT</h2>


<h2>Upload Image</h2>
<p>
@using (Html.BeginForm("UploadTvT", "BuilkProject1", FormMethod.Post, new { enctype = "multipart/form-data" }))
{ 
    <input type = "file" name="image" />
    <input type = "submit" value="Upload" />
    
}
</p>